---
title: "Lab 03 - Nobel laureates"
author: "Insert your name here"
date: "Insert date here"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1

```{r}
dim(nobel)
```


### Exercise 2

```{r}
nobel_living <- filter(nobel, 
                       !is.na(country),
                       gender != "org",
                       is.na(died_date))
```
```{r}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
```


### Exercise 3


```{r}
ggplot(nobel_living_science, aes(y = country_us)) +
  geom_bar() +
  facet_grid(~ category) +
  labs(title = "Are they USA-based?", x = "Country", y = "Counts") +
  theme_minimal()
```

### Exercise 4

...
```{r}
nobel_living <- nobel_living %>%
  mutate(
    born_us = if_else(born_country == "USA", "Born USA", "Born Other")
  )
nobel_living_science_born <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
```

### Exercise 5

...
```{r}
ggplot(nobel_living_science_born, aes(y = country_us, fill = born_us)) +
  geom_bar() +
  facet_grid(~ category) +
  labs(title = "Are they USA-based/born?", x = "Country", y = "Counts") +
  theme_minimal()
```

### Exercise 6
```{r}
outsiders <- nobel_living %>%
  filter(born_country != "USA"
  )
count(outsiders, born_country, wt = NULL, sort = TRUE)
```


...
